---
- name: Create the repo directories
  file:
    state: directory
    path: "{{ item }}"
    owner: "{{ role_dir_owner | default(omit) }}"
    group: "{{ role_dir_group | default(omit) }}"
    mode: "{{ role_dir_mode | default(omit) }}"
  with_items:
    - "{{ role_dir_path | mandatory }}"
    - "{{ role_dir_path | mandatory }}/defaults"
    - "{{ role_dir_path | mandatory }}/meta"
    - "{{ role_dir_path | mandatory }}/test"

- name: Put in the default template files
  template:
    src: "{{ item.value.template }}"
    dest: "{{ item.value.path}}"
    owner: "{{ role_dir_owner | default(omit) }}"
    group: "{{ role_dir_group | default(omit) }}"
    mode: "{{ role_dir_mode | default(omit) }}"
  with_dict: role_templates


...
